CREATE DATABASE pi;
USE pi;

CREATE TABLE usuario (
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR (45),
email VARCHAR(100),
senha VARCHAR(45),
CPF CHAR (12) UNIQUE,
DTCadastro DATETIME DEFAULT CURRENT_TIMESTAMP
 ) AUTO_INCREMENT = 1000;

CREATE TABLE sensores (
id_sensor INT PRIMARY KEY AUTO_INCREMENT,
id_empresa INT,
locais CHAR (8),
dados CHAR (4));

CREATE TABLE calculo  (
id_calc INT PRIMARY KEY AUTO_INCREMENT,
dado_Temp CHAR (4),
dado_Umidade CHAR (4));

 